defaults: &defaults
  adapter: mysql2
  username: johnnydepp
  password: Tr9o1CucA
  reconnect: true
  host: 10.180.170.36
  encoding: utf8

development: &development
  # <<: *defaults
  hostname: 127.0.0.1
  database: fiverr_dev
  socket: /tmp/mysql.sock
  adapter: mysql2
  username: root
  password: 
  reconnect: true

production: &production
  <<: *defaults
  host: 10.180.160.71
  database: fiverr_prod
  slow_slave:
    <<: *defaults
    host: 10.180.170.36
    database: fiverr_prod
    port: 3309
  slave01:
    <<: *defaults
    host: 10.180.170.36
    database: fiverr_prod
    port: 3306
  user_sales_slave:
    <<: *defaults
    host: 10.180.170.36
    database: fiverr_prod
    port: 3310
  buyables_master:
    <<: *defaults
    host: 10.180.134.49
    database: fiverr_prod
    port: 3306
  buyables_slave:
    <<: *defaults
    host: 10.180.170.36
    database: fiverr_prod
    port: 3316
  orders_master:
    <<: *defaults
    host: 10.180.170.36
    database: fiverr_orders
    port: 3311
  orders_slave:
    <<: *defaults
    host: 10.180.170.36
    database: fiverr_orders
    port: 3312
  conv_master:
    <<: *defaults
    host: 10.180.147.221
    database: fiverr_prod
    port: 3306
  conv_slave:
    <<: *defaults
    host: 10.180.170.36
    database: fiverr_prod
    port: 3314