development:
  max_experiment_duration_in_days: 60
  experiment_data_store: auto # cookie, redis, auto
  global_kpis:
    - ftb
    - ftg
  fast_storage:
    host: 127.0.0.1
    port: 6379

production:
  max_experiment_duration_in_days: 60
  experiment_data_store: auto # cookie, redis, auto
  fast_storage:
    host: 10.181.17.2
    port: 6382

test:
  max_experiment_duration_in_days: 60
  experiment_data_store: auto # cookie, redis, auto
  fast_storage:
    host: 127.0.0.1
    port: 6379