development: &development
  host: 127.0.0.1
  port: 6379

beta:
  host: 127.0.0.1
  port: 6379

test: &test
  host: 127.0.0.1
  port: 6379

cucumber: &cucumber
  host: 127.0.0.1
  port: 6379

staging: &staging
  host: 10.177.167.120
  port: 6382

production: &production
  host: 10.181.17.2
  port: 6382

backoffice: &backoffice
  host: 10.177.205.253
  port: 6382
